name: Build LaTeX document
on:
  push:
    tags:
      - "*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile Latex template
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run latex cv/cv.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: cv/
          root_file: cv.tex
          latexmk_use_xelatex: true
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cv/cv.pdf
            src/info.json
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "cv/cv.pdf"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "Jordan Ayala - Resume.pdf"
          overwrite: "true"
permissions:
  contents: write
